### ISSUE TITLE
transformWidth breakpoint causing inputs to lose focus on keyboard input 

### ISSUE THREAD

**Issue by btechgroup** [maslianok/react-responsive-tabs#50]
Hi,

transformWidth breakpoint causing inputs to lose focus on keyboard input.  When screen size is lower than the transformWidth and tabs are converted to accordion, it is causing the form inputs to lose focus.

Regards,
Ahmed, Btech

**Comment by maslianok** [comment]
Sorry for the huge delay with the response. Finally, I have time to review all the issues for this library.
And I think it's better late than never :)

You're right.
A TabPanel gets unmounted and mounted again. That's why all inputs inside lose focus. Unfortunately, I don't know how to build the same logic without remounting.

To solve your problem I would add some additional React logic:
- add refs to all inputs and save focused input to the state
- add resize handler (`react-resize-detector` is very fast and React friendly)
- when tabs get transformed - restore focus from the state (e.g. `refs[this.state.focusedInput].focus()`)
